spring:
  application:
    name: game-server-manager

server:
  address: ${GAME_SERVER_MANAGER_ADDRESS:127.0.0.1}
  port: ${GAME_SERVER_MANAGER_PORT:8080}

game-server-manager:
  storage:
    root: "C:\\GameServerManager"
